-- MySQL Script generated by MySQL Workbench
-- Thu Mar  2 19:35:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_bd` DEFAULT CHARACTER SET utf8 ;
USE `project_bd` ;

-- -----------------------------------------------------
-- Table `project_bd`.`Position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Position` (
  `id_pos` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_pos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_bd`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Employee` (
  `id_emp` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(100) NOT NULL,
  `id_pos` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_emp`),
  INDEX `position_idx` (`id_pos` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `fullname_UNIQUE` (`fullname` ASC) VISIBLE,
  CONSTRAINT `position`
    FOREIGN KEY (`id_pos`)
    REFERENCES `project_bd`.`Position` (`id_pos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_bd`.`Manager's account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Manager's account` (
  `id_mngr` INT NOT NULL AUTO_INCREMENT,
  `id_emp` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_mngr`),
  INDEX `employee_idx` (`id_emp` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  CONSTRAINT `employee1`
    FOREIGN KEY (`id_emp`)
    REFERENCES `project_bd`.`Employee` (`id_emp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_bd`.`Form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Form` (
  `id_form` INT NOT NULL AUTO_INCREMENT,
  `id_mngr` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `deadline` DATETIME NOT NULL,
  `description` VARCHAR(455) NOT NULL,
  `content` JSON NOT NULL,
  PRIMARY KEY (`id_form`),
  INDEX `form_idx` (`id_mngr` ASC) VISIBLE,
  CONSTRAINT `manager1`
    FOREIGN KEY (`id_mngr`)
    REFERENCES `project_bd`.`Manager's account` (`id_mngr`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_bd`.`Interviewed account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Interviewed account` (
  `id_int_acc` INT NOT NULL AUTO_INCREMENT,
  `id_emp` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_int_acc`),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  INDEX `employee_idx` (`id_emp` ASC) VISIBLE,
  CONSTRAINT `employee2`
    FOREIGN KEY (`id_emp`)
    REFERENCES `project_bd`.`Employee` (`id_emp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_bd`.`Interviewed X form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Interviewed X form` (
  `id_int_form` INT NOT NULL AUTO_INCREMENT,
  `id_form` INT NOT NULL,
  `id_int` INT NOT NULL,
  PRIMARY KEY (`id_int_form`),
  INDEX `form_idx` (`id_form` ASC) VISIBLE,
  INDEX `interviewed_idx` (`id_int` ASC) VISIBLE,
  CONSTRAINT `form1`
    FOREIGN KEY (`id_form`)
    REFERENCES `project_bd`.`Form` (`id_form`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `interviewed1`
    FOREIGN KEY (`id_int`)
    REFERENCES `project_bd`.`Interviewed account` (`id_int_acc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_bd`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Groups` (
  `id_grp` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_grp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_bd`.`Interviewed X group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Interviewed X group` (
  `id_int_grp` INT NOT NULL AUTO_INCREMENT,
  `id_int` INT NOT NULL,
  `id_grp` INT NOT NULL,
  PRIMARY KEY (`id_int_grp`),
  INDEX `group_idx` (`id_grp` ASC) VISIBLE,
  INDEX `interviewed_idx` (`id_int` ASC) VISIBLE,
  CONSTRAINT `interviewed3`
    FOREIGN KEY (`id_int`)
    REFERENCES `project_bd`.`Interviewed account` (`id_int_acc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group1`
    FOREIGN KEY (`id_grp`)
    REFERENCES `project_bd`.`Groups` (`id_grp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_bd`.`Reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Reply` (
  `id_rpl` INT NOT NULL AUTO_INCREMENT,
  `id_form` INT NOT NULL,
  `id_int` INT NOT NULL,
  `text` VARCHAR(900) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_rpl`),
  INDEX `form_idx` (`id_form` ASC) VISIBLE,
  INDEX `interviewed_idx` (`id_int` ASC) VISIBLE,
  CONSTRAINT `form2`
    FOREIGN KEY (`id_form`)
    REFERENCES `project_bd`.`Form` (`id_form`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `interviewed2`
    FOREIGN KEY (`id_int`)
    REFERENCES `project_bd`.`Interviewed account` (`id_int_acc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_bd`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Status` (
  `id_stat` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_stat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_bd`.`Content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Content` (
  `id_cont` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(455) NOT NULL,
  PRIMARY KEY (`id_cont`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_bd`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Notification` (
  `id_ntf` INT NOT NULL AUTO_INCREMENT,
  `id_form` INT NOT NULL,
  `id_stat` INT NOT NULL,
  `id_send` INT NOT NULL,
  `id_cont` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_ntf`),
  INDEX `form_idx` (`id_form` ASC) VISIBLE,
  INDEX `status_idx` (`id_stat` ASC) VISIBLE,
  INDEX `content_idx` (`id_cont` ASC) VISIBLE,
  INDEX `interviewed_idx` (`id_send` ASC) VISIBLE,
  CONSTRAINT `form4`
    FOREIGN KEY (`id_form`)
    REFERENCES `project_bd`.`Form` (`id_form`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `status`
    FOREIGN KEY (`id_stat`)
    REFERENCES `project_bd`.`Status` (`id_stat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `content`
    FOREIGN KEY (`id_cont`)
    REFERENCES `project_bd`.`Content` (`id_cont`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `interviewed4`
    FOREIGN KEY (`id_send`)
    REFERENCES `project_bd`.`Interviewed account` (`id_int_acc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_bd`.`Admin's account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_bd`.`Admin's account` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `id_emp` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_admin`),
  INDEX `employee_idx` (`id_emp` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  CONSTRAINT `employee3`
    FOREIGN KEY (`id_emp`)
    REFERENCES `project_bd`.`Employee` (`id_emp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
